### ISSUE TITLE
Add a feature to deal with family classification

### ISSUE THREAD

**Issue by gcgbarbosa** [EnquistLab/TNRSweb#3]
From the instructoins found [here](http://tnrs.iplantcollaborative.org/instructions.html#classification):

```
By default, the TNRS will return the classification for family according to the APGIII classification if you have selected more than one source. 
If you select only one source, the family will be displayed for that source. 
In this case, if you have selected a source of USDA only, you will get the family classification for USDA only (which is very similar to the APGIII classification schema).
```

We need to add:
1. An endpoint to the API that returns these classification options
2. A functionality to dynamically load the sources from the API on the `frontend`

**Comment by ojalaquellueva** [comment]
Actually, the family classification is independent of taxonomic source. It is applied to all sources, regardless of which are selected. Currently we have only APGIII, which also happens to be the classification used by Tropicos. But it's also possible would could add another, different classification in the future. The key point is that the selected classification has to be comprehensive, meaning it includes all species in all the others sources as well. Mapping a family classification used by one source (e.g., Tropicos) to another source (e.g., usda or tpl) is a complicated decision tree because different source usually have unique species or genera not shared with the others. However, this mapping process is performed in advance and cached when building the database. All the app has to do is look up the available family classifications, select one, and use it.

**Comment by gcgbarbosa** [comment]
Thanks for clarifying this, @ojalaquellueva.
I think from the last meeting we are going to get these from the API already, so all good :)

By the next meeting, we wanna have these options being loaded from the API, but I won't hesitate to ask if I need it.
